version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
      
    steps:
      - checkout
      - run: 
          name: Install NPM
          command: cd ./Template/DotnetTemplate/AngularApp && npm install && cd ../../../

      - save_cache:
          key: npm-cache-{{ checksum "./Template/DotnetTemplate/AngularApp/package.json" }}
          paths: ./angular5dotnetcore2.0/dotnetcoreplusangular5Template/AngularApp/node_modules

      - run:
          name: NPM build
          command: npm run build --prefix ./Template/DotnetTemplate/AngularApp

    #   - run:
    #       name: Lint Project
    #       command: npm run lint --prefix ./Template/DotnetTemplate/AngularApp

     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $Docker_UserName -p $Docker_Password

     # build the application image
     - run: docker build -t $Docker_Repo:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push $Docker_Repo:$CIRCLE_BRANCH